version: '2'
services:
    rethinkdb-container:
        restart: always
        image: rethinkdb
        hostname: rethinkdb
        volumes:
            - "/isard/database:/data"
        expose:
            - "28015"
        networks:
            main:
                aliases:
                - rethinkdb

    isard-hypervisor:
        restart: always
        image: isard/hypervisor
        links:
            - "rethinkdb-container"
        hostname: isard-hypervisor
        ports:
            - "80:80"
            - "5900-5930:5900-5930"
            - "55900-55930:55900-55930"
        expose:
            - "22"
        privileged: true
        volumes:
            - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
            - "sshkeys:/root/.ssh"
            - "/isard:/isard"
            - "/isard/builder:/root/.cache/virt-builder"
            - "/etc/hostname:/hostname"
            - "viewerkeys:/etc/pki/libvirt-spice"
        networks:
            main:
                aliases:
                - isard-hypervisor
        command: /usr/sbin/init

    isard-webapp:
        restart: always
        image: isard/webapp
        links:
            - "rethinkdb-container"
        hostname: isard-webapp
        volumes:
            - "viewerkeys:/isard/install/viewer-certs"
            - "/isard/logs:/isard/logs"
        expose:
            - "5000"
        environment:
            PYTHONUNBUFFERED: 0
        networks:
            main:
                aliases:
                - isard-webapp
        command: bash -c '/init.sh'

    isard-engine:
        restart: always
        image: isard/engine
        links:
            - "rethinkdb-container"
            - "isard-hypervisor"
        volumes:
            - "sshkeys:/root/.ssh"
            - "/isard/logs:/isard/logs"
        hostname: isard-engine
        expose:
            - "5555"
        environment:
            PYTHONUNBUFFERED: 0
        networks:
            main:
                aliases:
                - isard-engine
        command: bash -c '/init.sh'

    isard-nginx:
        restart: always
        image: isard/nginx
        ports:
            - "443:443"
        hostname: isard-nginx
        links:
            - "isard-webapp:isard-webapp"
        networks:
            main:
                aliases:
                - isard-nginx

networks:
    main:
volumes:
    sshkeys:
    viewerkeys:
